name: JS linting and tests

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name:    JS linting
    runs-on: ubuntu-latest
    steps:
      # clone the repository
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      # enable dependencies caching
      - uses: actions/cache@v4
        with:
          path: ~/.cache/composer/
          key:  ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
      # install dependencies and run linter
      - run: pnpm install --frozen-lockfile && pnpm run lint:js && pnpm run lint:css

  test:
    name:    JS testing
    runs-on: ubuntu-latest
    steps:
      # clone the repository
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      # enable dependencies caching
      - uses: actions/cache@v4
        with:
          path: ~/.cache/composer/
          key:  ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      # install dependencies and run linter
      - run: pnpm install --frozen-lockfile && pnpm run test:js
